ERR_COULD_NOT_LOCALIZE = (1, 'Robot could not get localized')
ERR_COULD_NOT_NAV_TO_WAREHOUSE = (2, 'Could not navigate to warehouse')
ERR_COULD_NOT_NAV_TO_CART = (3, 'Could not navigate to cart')
ERR_COULD_NOT_NAV_TO_DELIVERY_POINT = (4, 'Could not navigate to delivery point')
ERR_NAV_RETURN_WAREHOUSE_FAILED = (5, 'Could not navigate to warehouse to return the cart')
